
services:
  crypto-signal-ai:
    build: .
    container_name: crypto_ai_app
    image: cryptosignal:latest
    ports:
      - "20000:20000"
    environment:
      # Thay Key thật của bạn vào đây
      - API_KEY=AIzaSyCzk9WrtTRQe1xsffRMk68ytP6EsrFdfPo
    restart: always
