
services:
  crypto-signal-ai:
    build: .
    container_name: crypto_ai_app
    ports:
      - "20000:80"
    environment:
      # LƯU Ý: Thay thế bằng API Key Gemini thật của bạn
      - API_KEY=AIzaSyD2tunq1jkMExaYRz0pbVKw-06M_JbDEGg
    restart: always
