
services:
  crypto-signal-ai:
    build: .
    container_name: crypto_ai_app
    ports:
      - "20000:80"
    environment:
      # Thay Key thật của bạn vào đây
      - API_KEY=AIzaSyCpyPu6zZAbj4ZVafQhXq_QzucoMoA2dU8
    restart: always
