
services:
  crypto-signal-ai:
    build: .
    image: cryptosignal:latest
    container_name: crypto_ai_app
    ports:
      - "20000:80"
    environment:
      - API_KEY=AIzaSyD2tunq1jkMExaYRz0pbVKw-06M_JbDEGg
    restart: always
