
services:
  crypto-signal-ai:
    build: .
    container_name: crypto_ai_app
    ports:
      - "20000:20000"
    environment:
      # LƯU Ý: Thay thế bằng API Key Gemini thật của bạn
      - API_KEY=AIzaSyBIC54-4wiFJfHV7oyFfyhJpKERvfyUars
    restart: always
